SET NAMES utf8mb4;
CREATE DATABASE IF NOT EXISTS `hear_like_me`
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;
USE `hear_like_me`;

CREATE TABLE `challenge_audio_bank` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `audio_code` varchar(64) NOT NULL COMMENT '音频唯一编码',
  `title` varchar(150) NOT NULL COMMENT '音频名称',
  `description` varchar(500) DEFAULT NULL COMMENT '素材说明',
  `source_asset_id` bigint NOT NULL COMMENT '原始音频 file_asset.id',
  `output_asset_id` bigint DEFAULT NULL COMMENT '生成后的模拟音频 file_asset.id',
  `processing_task_no` varchar(64) DEFAULT NULL COMMENT '最近一次处理任务编号',
  `n_channels` tinyint NOT NULL COMMENT '有效通道数，同时作为挑战正确答案',
  `carrier` varchar(20) NOT NULL DEFAULT 'noise' COMMENT 'noise/sine',
  `f_lo` decimal(10,2) NOT NULL DEFAULT '150.00' COMMENT '频率下限 Hz',
  `f_hi` decimal(10,2) NOT NULL DEFAULT '7000.00' COMMENT '频率上限 Hz',
  `env_cut` decimal(10,2) NOT NULL DEFAULT '160.00' COMMENT '包络低通截止 Hz',
  `spread` decimal(6,4) NOT NULL DEFAULT '0.1500' COMMENT '电流扩散 0-1',
  `noise_level` decimal(6,4) NOT NULL DEFAULT '0.0000' COMMENT '背景噪声 0-1',
  `version_no` int NOT NULL DEFAULT '0' COMMENT '成功生成版本号',
  `status` varchar(20) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/PROCESSING/READY/FAILED/DISABLED',
  `error_message` varchar(500) DEFAULT NULL COMMENT '最近一次生成失败原因',
  `generated_time` datetime DEFAULT NULL COMMENT '最近生成成功时间',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_delete` tinyint NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_challenge_audio_code` (`audio_code`),
  KEY `idx_challenge_audio_status` (`status`,`is_delete`),
  KEY `idx_challenge_audio_source` (`source_asset_id`),
  KEY `idx_challenge_audio_output` (`output_asset_id`),
  CONSTRAINT `fk_challenge_audio_source` FOREIGN KEY (`source_asset_id`) REFERENCES `file_asset` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_challenge_audio_output` FOREIGN KEY (`output_asset_id`) REFERENCES `file_asset` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `chk_challenge_audio_channels` CHECK (`n_channels` IN (2,4,8,16)),
  CONSTRAINT `chk_challenge_audio_carrier` CHECK (`carrier` IN ('noise','sine')),
  CONSTRAINT `chk_challenge_audio_status` CHECK (`status` IN ('DRAFT','PROCESSING','READY','FAILED','DISABLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='听音挑战音频库';

CREATE TABLE `hearing_challenge` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `question_code` varchar(64) NOT NULL COMMENT '题目唯一编码，如 vowel-8ch-001',
  `title` varchar(150) NOT NULL COMMENT '后台题目名称，如 元音示例·8通道',
  `description` varchar(500) DEFAULT NULL COMMENT '题目/素材备注，仅用于后台管理或前端辅助说明',
  `audio_bank_id` bigint DEFAULT NULL COMMENT '引用的挑战音频库记录；本地直传模拟音时可为空',
  `audio_asset_id` bigint NOT NULL COMMENT '挑战最终音频，对应 file_asset.id',
  `n_channels` tinyint NOT NULL COMMENT '有效通道数；第一版仅允许 2/4/8/16，也是本题正确答案',
  `carrier` varchar(20) NOT NULL DEFAULT 'noise' COMMENT '载体类型：noise/sine',
  `f_lo` decimal(10,2) NOT NULL DEFAULT '150.00' COMMENT '频率下限 Hz',
  `f_hi` decimal(10,2) NOT NULL DEFAULT '7000.00' COMMENT '频率上限 Hz',
  `env_cut` decimal(10,2) NOT NULL DEFAULT '160.00' COMMENT '包络低通截止 Hz',
  `spread` decimal(6,4) NOT NULL DEFAULT '0.1500' COMMENT '电流扩散 0-1',
  `noise_level` decimal(6,4) NOT NULL DEFAULT '0.0000' COMMENT '背景噪声 0-1',
  `env_amp` decimal(8,4) NOT NULL DEFAULT '2.6000' COMMENT '包络增益',
  `wet_mix` decimal(6,4) NOT NULL DEFAULT '0.9000' COMMENT '处理后声音混合比例 0-1',
  `compress_enabled` tinyint NOT NULL DEFAULT '1' COMMENT '是否启用动态压缩：0否 1是',
  `normalize_peak` decimal(6,4) DEFAULT '0.8900' COMMENT '归一化峰值；NULL=关闭',
  `correct_tip` varchar(500) DEFAULT NULL COMMENT '答对后的补充说明',
  `wrong_tip` varchar(500) DEFAULT NULL COMMENT '答错后的补充说明',
  `status` varchar(20) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/PUBLISHED/OFFLINE',
  `sort_order` int NOT NULL DEFAULT '0' COMMENT '排序值，越小越靠前',
  `published_time` datetime DEFAULT NULL COMMENT '首次/最近发布时间',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_delete` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除：0否 1是',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_hearing_challenge_code` (`question_code`),
  KEY `idx_hearing_challenge_audio_bank` (`audio_bank_id`),
  KEY `idx_hearing_challenge_audio` (`audio_asset_id`),
  KEY `idx_hearing_challenge_status_sort` (`status`,`sort_order`),
  KEY `idx_hearing_challenge_channels` (`n_channels`),
  CONSTRAINT `fk_hearing_challenge_audio` FOREIGN KEY (`audio_asset_id`) REFERENCES `file_asset` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_hearing_challenge_audio_bank` FOREIGN KEY (`audio_bank_id`) REFERENCES `challenge_audio_bank` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `chk_hearing_challenge_carrier` CHECK ((`carrier` in (_utf8mb4'noise',_utf8mb4'sine'))),
  CONSTRAINT `chk_hearing_challenge_channels` CHECK ((`n_channels` in (2,4,8,16))),
  CONSTRAINT `chk_hearing_challenge_env` CHECK ((`env_cut` between 20 and 500)),
  CONSTRAINT `chk_hearing_challenge_frequency` CHECK (((`f_lo` > 0) and (`f_hi` > `f_lo`))),
  CONSTRAINT `chk_hearing_challenge_noise` CHECK ((`noise_level` between 0 and 1)),
  CONSTRAINT `chk_hearing_challenge_normalize` CHECK (((`normalize_peak` is null) or ((`normalize_peak` > 0) and (`normalize_peak` <= 1)))),
  CONSTRAINT `chk_hearing_challenge_spread` CHECK ((`spread` between 0 and 1)),
  CONSTRAINT `chk_hearing_challenge_status` CHECK ((`status` in (_utf8mb4'DRAFT',_utf8mb4'PUBLISHED',_utf8mb4'OFFLINE'))),
  CONSTRAINT `chk_hearing_challenge_wet` CHECK ((`wet_mix` between 0 and 1))
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='听音挑战题库：后台上传处理后音频并配置模拟参数，小程序用于猜有效通道数';
